//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOSM1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Other
    {
        public string Welcome_message { get; set; }
        public string Contact_info { get; set; }
        public long OtherID { get; set; }
    }
}
